///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Scenario3
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Scenario3Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("7f437a4b-0584-4c34-997f-239fd71de96b")]
    public partial class Scenario3Repository : RepoGenBaseFolder
    {
        static Scenario3Repository instance = new Scenario3Repository();
        Scenario3RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the Scenario3Repository element repository.
        /// </summary>
        [RepositoryFolder("7f437a4b-0584-4c34-997f-239fd71de96b")]
        public static Scenario3Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Scenario3Repository() 
            : base("Scenario3Repository", "/", null, 0, false, "7f437a4b-0584-4c34-997f-239fd71de96b", ".\\RepositoryImages\\Scenario3Repository7f437a4b.rximgres")
        {
            _applicationundertest = new Scenario3RepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7f437a4b-0584-4c34-997f-239fd71de96b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("61455a73-916d-4b96-a0b9-1419121d9dc0")]
        public virtual Scenario3RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Scenario3RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("61455a73-916d-4b96-a0b9-1419121d9dc0")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _girişyapInfo;
            RepoItemInfo _registeremailInfo;
            RepoItemInfo _registerpasswordinputInfo;
            RepoItemInfo _tycheckInfo;
            RepoItemInfo _ueyeolInfo;
            RepoItemInfo _epostaveşifrenizigirinizInfo;
            RepoItemInfo _ueyeol1Info;
            RepoItemInfo _buepostaadresikullanılamazluetfenInfo;
            RepoItemInfo _şifreniz7ile15karakterarasındaolmaInfo;
            RepoItemInfo _fill1Info;
            RepoItemInfo _qbuttonqbuttonmediumqfluidqprimaInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.trendyol.com']", parentFolder, 30000, null, false, "61455a73-916d-4b96-a0b9-1419121d9dc0", "")
            {
                _girişyapInfo = new RepoItemInfo(this, "GirişYap", ".//div[#'account-navigation-container']/div/div[1]/?/?/p[@innertext='Giriş Yap']", ".//div[#'account-navigation-container']//p[@innertext='Giriş Yap']", 30000, null, "bd156b7b-c82b-45c2-815e-04c4674b4e2b");
                _registeremailInfo = new RepoItemInfo(this, "RegisterEmail", ".//input[#'register-email']", ".//input[#'register-email']", 30000, null, "5b39cb75-b67c-4150-b5d6-2c9fd27f1483");
                _registerpasswordinputInfo = new RepoItemInfo(this, "RegisterPasswordInput", ".//input[#'register-password-input']", ".//input[#'register-password-input']", 30000, null, "ff7e3a15-f0f6-43dd-af99-1f4c64ab23f4");
                _tycheckInfo = new RepoItemInfo(this, "TyCheck", ".//div[#'login-register']/div[3]/?/?/form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']/div[6]//svg", ".//div[#'login-register']//form/div[6]/div/div[1]/div/svg", 30000, null, "6b1c6dd8-f20c-44f5-ab2e-f0c5a5279bf3");
                _ueyeolInfo = new RepoItemInfo(this, "UEyeOl", ".//div[#'login-register']//form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']/?/?/span[@innertext='Üye Ol']", ".//div[#'login-register']//form/button/span[@innertext='Üye Ol']", 30000, null, "56f35c51-c1cd-4f4f-a5a0-2755878bcfd9");
                _epostaveşifrenizigirinizInfo = new RepoItemInfo(this, "EPostaVeŞifreniziGiriniz", ".//div[#'error-box-wrapper']/span[@innertext>'E-posta ve şifrenizi giri']", ".//div[#'error-box-wrapper']/span[@innertext>'E-posta ve şifrenizi giri']", 30000, null, "a8a170f0-8463-4126-8b39-39f2b53000f8");
                _ueyeol1Info = new RepoItemInfo(this, "UEyeOl1", ".//div[#'login-register']/div[2]/div/button[2]/span[@innertext='Üye Ol']", ".//div[#'login-register']//span[@innertext='Üye Ol']", 30000, null, "73b55ef4-e25a-4e83-bc2e-0e8558c010f4");
                _buepostaadresikullanılamazluetfenInfo = new RepoItemInfo(this, "BuEPostaAdresiKullanılamazLuetfen", ".//div[#'error-box-wrapper']/span[@innertext>'Bu e-posta adresi kullanılamaz.']", ".//div[#'error-box-wrapper']/span[@innertext>'Bu e-posta adresi kullanılamaz.']", 30000, null, "f6714f7d-90a7-4995-8a14-7d4222599ca1");
                _şifreniz7ile15karakterarasındaolmaInfo = new RepoItemInfo(this, "Şifreniz7Ile15KarakterArasındaOlma", ".//div[#'error-box-wrapper']/span[@innertext>'Şifreniz 7 ile 15 karakter']", ".//div[#'error-box-wrapper']/span[@innertext>'Şifreniz 7 ile 15 karakter']", 30000, null, "2470ac80-4dbb-4ab2-9de8-434be3dac8cf");
                _fill1Info = new RepoItemInfo(this, "Fill1", ".//div[#'login-register']/div[3]/div[1]/form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']/div[6]/div/div[1]//use[@id='Fill-1']", ".//div[#'login-register']//form/div[6]/div/div[1]/div/svg/g/g/g/g/use[@id='Fill-1']", 30000, null, "dd6fa259-5a53-4f45-b514-b760fab0af37");
                _qbuttonqbuttonmediumqfluidqprimaInfo = new RepoItemInfo(this, "QButtonQButtonMediumQFluidQPrima", ".//div[#'login-register']//form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']/button", ".//div[#'login-register']//form/button", 30000, null, "0ad95fb2-505c-400a-a5de-6c90d8ccdb24");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("61455a73-916d-4b96-a0b9-1419121d9dc0")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("61455a73-916d-4b96-a0b9-1419121d9dc0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GirişYap item.
            /// </summary>
            [RepositoryItem("bd156b7b-c82b-45c2-815e-04c4674b4e2b")]
            public virtual Ranorex.PTag GirişYap
            {
                get
                {
                    return _girişyapInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap item info.
            /// </summary>
            [RepositoryItemInfo("bd156b7b-c82b-45c2-815e-04c4674b4e2b")]
            public virtual RepoItemInfo GirişYapInfo
            {
                get
                {
                    return _girişyapInfo;
                }
            }

            /// <summary>
            /// The RegisterEmail item.
            /// </summary>
            [RepositoryItem("5b39cb75-b67c-4150-b5d6-2c9fd27f1483")]
            public virtual Ranorex.InputTag RegisterEmail
            {
                get
                {
                    return _registeremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterEmail item info.
            /// </summary>
            [RepositoryItemInfo("5b39cb75-b67c-4150-b5d6-2c9fd27f1483")]
            public virtual RepoItemInfo RegisterEmailInfo
            {
                get
                {
                    return _registeremailInfo;
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item.
            /// </summary>
            [RepositoryItem("ff7e3a15-f0f6-43dd-af99-1f4c64ab23f4")]
            public virtual Ranorex.InputTag RegisterPasswordInput
            {
                get
                {
                    return _registerpasswordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("ff7e3a15-f0f6-43dd-af99-1f4c64ab23f4")]
            public virtual RepoItemInfo RegisterPasswordInputInfo
            {
                get
                {
                    return _registerpasswordinputInfo;
                }
            }

            /// <summary>
            /// The TyCheck item.
            /// </summary>
            [RepositoryItem("6b1c6dd8-f20c-44f5-ab2e-f0c5a5279bf3")]
            public virtual Ranorex.SvgTag TyCheck
            {
                get
                {
                    return _tycheckInfo.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The TyCheck item info.
            /// </summary>
            [RepositoryItemInfo("6b1c6dd8-f20c-44f5-ab2e-f0c5a5279bf3")]
            public virtual RepoItemInfo TyCheckInfo
            {
                get
                {
                    return _tycheckInfo;
                }
            }

            /// <summary>
            /// The UEyeOl item.
            /// </summary>
            [RepositoryItem("56f35c51-c1cd-4f4f-a5a0-2755878bcfd9")]
            public virtual Ranorex.SpanTag UEyeOl
            {
                get
                {
                    return _ueyeolInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOl item info.
            /// </summary>
            [RepositoryItemInfo("56f35c51-c1cd-4f4f-a5a0-2755878bcfd9")]
            public virtual RepoItemInfo UEyeOlInfo
            {
                get
                {
                    return _ueyeolInfo;
                }
            }

            /// <summary>
            /// The EPostaVeŞifreniziGiriniz item.
            /// </summary>
            [RepositoryItem("a8a170f0-8463-4126-8b39-39f2b53000f8")]
            public virtual Ranorex.SpanTag EPostaVeŞifreniziGiriniz
            {
                get
                {
                    return _epostaveşifrenizigirinizInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The EPostaVeŞifreniziGiriniz item info.
            /// </summary>
            [RepositoryItemInfo("a8a170f0-8463-4126-8b39-39f2b53000f8")]
            public virtual RepoItemInfo EPostaVeŞifreniziGirinizInfo
            {
                get
                {
                    return _epostaveşifrenizigirinizInfo;
                }
            }

            /// <summary>
            /// The UEyeOl1 item.
            /// </summary>
            [RepositoryItem("73b55ef4-e25a-4e83-bc2e-0e8558c010f4")]
            public virtual Ranorex.SpanTag UEyeOl1
            {
                get
                {
                    return _ueyeol1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOl1 item info.
            /// </summary>
            [RepositoryItemInfo("73b55ef4-e25a-4e83-bc2e-0e8558c010f4")]
            public virtual RepoItemInfo UEyeOl1Info
            {
                get
                {
                    return _ueyeol1Info;
                }
            }

            /// <summary>
            /// The BuEPostaAdresiKullanılamazLuetfen item.
            /// </summary>
            [RepositoryItem("f6714f7d-90a7-4995-8a14-7d4222599ca1")]
            public virtual Ranorex.SpanTag BuEPostaAdresiKullanılamazLuetfen
            {
                get
                {
                    return _buepostaadresikullanılamazluetfenInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The BuEPostaAdresiKullanılamazLuetfen item info.
            /// </summary>
            [RepositoryItemInfo("f6714f7d-90a7-4995-8a14-7d4222599ca1")]
            public virtual RepoItemInfo BuEPostaAdresiKullanılamazLuetfenInfo
            {
                get
                {
                    return _buepostaadresikullanılamazluetfenInfo;
                }
            }

            /// <summary>
            /// The Şifreniz7Ile15KarakterArasındaOlma item.
            /// </summary>
            [RepositoryItem("2470ac80-4dbb-4ab2-9de8-434be3dac8cf")]
            public virtual Ranorex.SpanTag Şifreniz7Ile15KarakterArasındaOlma
            {
                get
                {
                    return _şifreniz7ile15karakterarasındaolmaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Şifreniz7Ile15KarakterArasındaOlma item info.
            /// </summary>
            [RepositoryItemInfo("2470ac80-4dbb-4ab2-9de8-434be3dac8cf")]
            public virtual RepoItemInfo Şifreniz7Ile15KarakterArasındaOlmaInfo
            {
                get
                {
                    return _şifreniz7ile15karakterarasındaolmaInfo;
                }
            }

            /// <summary>
            /// The Fill1 item.
            /// </summary>
            [RepositoryItem("dd6fa259-5a53-4f45-b514-b760fab0af37")]
            public virtual Ranorex.UseTag Fill1
            {
                get
                {
                    return _fill1Info.CreateAdapter<Ranorex.UseTag>(true);
                }
            }

            /// <summary>
            /// The Fill1 item info.
            /// </summary>
            [RepositoryItemInfo("dd6fa259-5a53-4f45-b514-b760fab0af37")]
            public virtual RepoItemInfo Fill1Info
            {
                get
                {
                    return _fill1Info;
                }
            }

            /// <summary>
            /// The QButtonQButtonMediumQFluidQPrima item.
            /// </summary>
            [RepositoryItem("0ad95fb2-505c-400a-a5de-6c90d8ccdb24")]
            public virtual Ranorex.ButtonTag QButtonQButtonMediumQFluidQPrima
            {
                get
                {
                    return _qbuttonqbuttonmediumqfluidqprimaInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The QButtonQButtonMediumQFluidQPrima item info.
            /// </summary>
            [RepositoryItemInfo("0ad95fb2-505c-400a-a5de-6c90d8ccdb24")]
            public virtual RepoItemInfo QButtonQButtonMediumQFluidQPrimaInfo
            {
                get
                {
                    return _qbuttonqbuttonmediumqfluidqprimaInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
