///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Scenario7
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Scenario7Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("303b5f2e-e3cd-4e8f-9a90-e6b099629816")]
    public partial class Scenario7Repository : RepoGenBaseFolder
    {
        static Scenario7Repository instance = new Scenario7Repository();
        Scenario7RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the Scenario7Repository element repository.
        /// </summary>
        [RepositoryFolder("303b5f2e-e3cd-4e8f-9a90-e6b099629816")]
        public static Scenario7Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Scenario7Repository() 
            : base("Scenario7Repository", "/", null, 0, false, "303b5f2e-e3cd-4e8f-9a90-e6b099629816", ".\\RepositoryImages\\Scenario7Repository303b5f2e.rximgres")
        {
            _applicationundertest = new Scenario7RepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("303b5f2e-e3cd-4e8f-9a90-e6b099629816")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("e85c5980-f670-44a9-9c45-af5b7c269c7f")]
        public virtual Scenario7RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Scenario7RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("e85c5980-f670-44a9-9c45-af5b7c269c7f")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            Scenario7RepositoryFolders.AccountNavItemUserLoginContainerFolder _accountnavitemuserlogincontainer;
            RepoItemInfo _girişyap1Info;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.trendyol.com']", parentFolder, 30000, null, false, "e85c5980-f670-44a9-9c45-af5b7c269c7f", "")
            {
                _accountnavitemuserlogincontainer = new Scenario7RepositoryFolders.AccountNavItemUserLoginContainerFolder(this);
                _girişyap1Info = new RepoItemInfo(this, "GirişYap1", ".//div[#'login-register']//form[@action='https://www.trendyol.com/giris?cb=https%3A%2F%2Fwww.trendyol.com%2F']/?/?/span[@innertext='Giriş Yap']", ".//div[#'login-register']//form/button/span[@innertext='Giriş Yap']", 30000, null, "b7c6e766-a556-4d20-a812-15308d147fcc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e85c5980-f670-44a9-9c45-af5b7c269c7f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e85c5980-f670-44a9-9c45-af5b7c269c7f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GirişYap1 item.
            /// </summary>
            [RepositoryItem("b7c6e766-a556-4d20-a812-15308d147fcc")]
            public virtual Ranorex.SpanTag GirişYap1
            {
                get
                {
                    return _girişyap1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap1 item info.
            /// </summary>
            [RepositoryItemInfo("b7c6e766-a556-4d20-a812-15308d147fcc")]
            public virtual RepoItemInfo GirişYap1Info
            {
                get
                {
                    return _girişyap1Info;
                }
            }

            /// <summary>
            /// The AccountNavItemUserLoginContainer folder.
            /// </summary>
            [RepositoryFolder("d17c46af-2b1f-4df3-9d17-b9dfc311304b")]
            public virtual Scenario7RepositoryFolders.AccountNavItemUserLoginContainerFolder AccountNavItemUserLoginContainer
            {
                get { return _accountnavitemuserlogincontainer; }
            }
        }

        /// <summary>
        /// The AccountNavItemUserLoginContainerFolder folder.
        /// </summary>
        [RepositoryFolder("d17c46af-2b1f-4df3-9d17-b9dfc311304b")]
        public partial class AccountNavItemUserLoginContainerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _girişyapInfo;
            RepoItemInfo _girişyap2Info;
            RepoItemInfo _cıkışyapInfo;
            RepoItemInfo _hesabımInfo;

            /// <summary>
            /// Creates a new AccountNavItemUserLoginContainer  folder.
            /// </summary>
            public AccountNavItemUserLoginContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("AccountNavItemUserLoginContainer", ".//div[#'account-navigation-container']/div/div[1]", parentFolder, 30000, null, false, "d17c46af-2b1f-4df3-9d17-b9dfc311304b", "")
            {
                _girişyapInfo = new RepoItemInfo(this, "GirişYap", ".//div[@innertext='Giriş Yap']", "", 30000, null, "4d2c89ed-21ec-4832-95cd-f65e8a87599b");
                _girişyap2Info = new RepoItemInfo(this, "GirişYap2", "?/?/p[@innertext='Giriş Yap']", "", 30000, null, "a023cd67-b064-4b6d-8785-b47ce6eed0df");
                _cıkışyapInfo = new RepoItemInfo(this, "CıkışYap", "div[2]/div/a[9]/p[@innertext='Çıkış Yap']", "", 30000, null, "6fa7e923-6a1a-4722-861a-851ab95a56b3");
                _hesabımInfo = new RepoItemInfo(this, "Hesabım", "?/?/p[@innertext='Hesabım']", "", 30000, null, "aafa51f5-6623-4810-91ca-305ce3ea4ed5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d17c46af-2b1f-4df3-9d17-b9dfc311304b")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d17c46af-2b1f-4df3-9d17-b9dfc311304b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GirişYap item.
            /// </summary>
            [RepositoryItem("4d2c89ed-21ec-4832-95cd-f65e8a87599b")]
            public virtual Ranorex.DivTag GirişYap
            {
                get
                {
                    return _girişyapInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap item info.
            /// </summary>
            [RepositoryItemInfo("4d2c89ed-21ec-4832-95cd-f65e8a87599b")]
            public virtual RepoItemInfo GirişYapInfo
            {
                get
                {
                    return _girişyapInfo;
                }
            }

            /// <summary>
            /// The GirişYap2 item.
            /// </summary>
            [RepositoryItem("a023cd67-b064-4b6d-8785-b47ce6eed0df")]
            public virtual Ranorex.PTag GirişYap2
            {
                get
                {
                    return _girişyap2Info.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap2 item info.
            /// </summary>
            [RepositoryItemInfo("a023cd67-b064-4b6d-8785-b47ce6eed0df")]
            public virtual RepoItemInfo GirişYap2Info
            {
                get
                {
                    return _girişyap2Info;
                }
            }

            /// <summary>
            /// The CıkışYap item.
            /// </summary>
            [RepositoryItem("6fa7e923-6a1a-4722-861a-851ab95a56b3")]
            public virtual Ranorex.PTag CıkışYap
            {
                get
                {
                    return _cıkışyapInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The CıkışYap item info.
            /// </summary>
            [RepositoryItemInfo("6fa7e923-6a1a-4722-861a-851ab95a56b3")]
            public virtual RepoItemInfo CıkışYapInfo
            {
                get
                {
                    return _cıkışyapInfo;
                }
            }

            /// <summary>
            /// The Hesabım item.
            /// </summary>
            [RepositoryItem("aafa51f5-6623-4810-91ca-305ce3ea4ed5")]
            public virtual Ranorex.PTag Hesabım
            {
                get
                {
                    return _hesabımInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Hesabım item info.
            /// </summary>
            [RepositoryItemInfo("aafa51f5-6623-4810-91ca-305ce3ea4ed5")]
            public virtual RepoItemInfo HesabımInfo
            {
                get
                {
                    return _hesabımInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
