///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Scenario6
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("5d7260c3-0fa6-4d05-9ce6-27dd19ea71ec", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Scenario6Repository repository.
        /// </summary>
        public static Scenario6Repository repo = Scenario6Repository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
            NewVariable = "/dom[@domain='www.trendyol.com']//div[#'account-navigation-container']/div/div[2]/a[@href>'https://www.trendyol.com/']/p[@innertext='Sepetim']";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _NewVariable;

        /// <summary>
        /// Gets or sets the value of variable NewVariable.
        /// </summary>
        [TestVariable("e993c958-4284-4956-878c-e8ccb29aae79")]
        public string NewVariable
        {
            get { return _NewVariable; }
            set { _NewVariable = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Sepetim' at 30;7.", repo.ApplicationUnderTest.SepetimInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Sepetim.Click("30;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'ApplicationUnderTest'.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Self.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SepetiOnayla' at 31;10.", repo.ApplicationUnderTest.SepetiOnaylaInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.SepetiOnayla.Click("31;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PLayout.PCheckboxText' at 10;8.", repo.ApplicationUnderTest.PLayout.PCheckboxTextInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.PLayout.PCheckboxText.Click("10;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PLayout.KaydetVeDevamEt' at 94;26.", repo.ApplicationUnderTest.PLayout.KaydetVeDevamEtInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.PLayout.KaydetVeDevamEt.Click("94;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.PLayout.KartBilgileri'.", repo.ApplicationUnderTest.PLayout.KartBilgileriInfo, new RecordItemIndex(5));
            Validate.Exists(repo.ApplicationUnderTest.PLayout.KartBilgileriInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.SonKullanmaTarihi'.", repo.ApplicationUnderTest.SonKullanmaTarihiInfo, new RecordItemIndex(6));
            Validate.Exists(repo.ApplicationUnderTest.SonKullanmaTarihiInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.CardCvv'.", repo.ApplicationUnderTest.CardCvvInfo, new RecordItemIndex(7));
            Validate.Exists(repo.ApplicationUnderTest.CardCvvInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.PLayout.KaydetVeDevamEt'.", repo.ApplicationUnderTest.PLayout.KaydetVeDevamEtInfo, new RecordItemIndex(8));
            Validate.Exists(repo.ApplicationUnderTest.PLayout.KaydetVeDevamEtInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
