///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Scenario6
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Scenario6Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("3530522d-8b76-4b5a-822a-0ebd69aac07c")]
    public partial class Scenario6Repository : RepoGenBaseFolder
    {
        static Scenario6Repository instance = new Scenario6Repository();
        Scenario6RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the Scenario6Repository element repository.
        /// </summary>
        [RepositoryFolder("3530522d-8b76-4b5a-822a-0ebd69aac07c")]
        public static Scenario6Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Scenario6Repository() 
            : base("Scenario6Repository", "/", null, 0, false, "3530522d-8b76-4b5a-822a-0ebd69aac07c", ".\\RepositoryImages\\Scenario6Repository3530522d.rximgres")
        {
            _applicationundertest = new Scenario6RepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3530522d-8b76-4b5a-822a-0ebd69aac07c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("ee61da31-70cc-42f7-b658-eccc4145274e")]
        public virtual Scenario6RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Scenario6RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("ee61da31-70cc-42f7-b658-eccc4145274e")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            Scenario6RepositoryFolders.PLayoutFolder _playout;
            Scenario6RepositoryFolders.LoginRegisterFolder _loginregister;
            RepoItemInfo _sepetimInfo;
            RepoItemInfo _sonkullanmatarihiInfo;
            RepoItemInfo _cardcvvInfo;
            RepoItemInfo _girişyapInfo;
            RepoItemInfo _loginemailInfo;
            RepoItemInfo _httpswwwtrendyolcomsepetInfo;
            RepoItemInfo _waitInfo;
            RepoItemInfo _sepetionaylaInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.trendyol.com']", parentFolder, 30000, null, false, "ee61da31-70cc-42f7-b658-eccc4145274e", "")
            {
                _playout = new Scenario6RepositoryFolders.PLayoutFolder(this);
                _loginregister = new Scenario6RepositoryFolders.LoginRegisterFolder(this);
                _sepetimInfo = new RepoItemInfo(this, "Sepetim", ".//div[#'account-navigation-container']/div/div[2]/a[@href>'https://www.trendyol.com/']/p[@innertext='Sepetim']", "", 40000, null, "5e74e8ef-1c5f-4522-b2f4-7dec3a23762c");
                _sonkullanmatarihiInfo = new RepoItemInfo(this, "SonKullanmaTarihi", ".//iframe[#'payment-fragment']/body//label[@innertext='Son Kullanma Tarihi']", ".//iframe[#'payment-fragment']//label[@innertext='Son Kullanma Tarihi']", 30000, null, "12867755-7f46-4c3f-845a-587e69064ba5");
                _cardcvvInfo = new RepoItemInfo(this, "CardCvv", ".//iframe[#'payment-fragment']//input[#'card-cvv']", ".//iframe[#'payment-fragment']//input[#'card-cvv']", 30000, null, "35b90ca0-6510-440a-a6a8-14dbc05a5498");
                _girişyapInfo = new RepoItemInfo(this, "GirişYap", ".//div[#'account-navigation-container']/div/div[1]/?/?/p[@innertext='Giriş Yap']", ".//div[#'account-navigation-container']//p[@innertext='Giriş Yap']", 30000, null, "dc81a9df-08f1-4207-b5f0-d28961770824");
                _loginemailInfo = new RepoItemInfo(this, "LoginEmail", ".//input[#'login-email']", ".//input[#'login-email']", 30000, null, "75af5ade-7813-4037-bad6-8e0df8ed0ec3");
                _httpswwwtrendyolcomsepetInfo = new RepoItemInfo(this, "HttpsWwwTrendyolComSepet", ".//div[#'account-navigation-container']/div/div[2]/a[@href>'https://www.trendyol.com/']", ".//div[#'account-navigation-container']/div/div[2]/a[@href>'https://www.trendyol.com/']", 30000, null, "3b40e370-a2aa-4742-96f3-41ace53527a3");
                _waitInfo = new RepoItemInfo(this, "wait", ".//div[#'account-navigation-container']/div/div[2]/a[@href>'https://www.trendyol.com/']/p[@innertext='Sepetim']", "element", 30000, null, "3be0e26a-e836-46e8-b81b-97b76299d122");
                _sepetionaylaInfo = new RepoItemInfo(this, "SepetiOnayla", ".//div[#'pb-container']/aside/div/div[1]/?/?/span[@innertext='Sepeti Onayla']", ".//div[#'pb-container']//span[@innertext='Sepeti Onayla']", 30000, null, "b4fa2eef-74f9-4704-a3da-80962e50ede2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ee61da31-70cc-42f7-b658-eccc4145274e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ee61da31-70cc-42f7-b658-eccc4145274e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Sepetim item.
            /// </summary>
            [RepositoryItem("5e74e8ef-1c5f-4522-b2f4-7dec3a23762c")]
            public virtual Ranorex.PTag Sepetim
            {
                get
                {
                    return _sepetimInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Sepetim item info.
            /// </summary>
            [RepositoryItemInfo("5e74e8ef-1c5f-4522-b2f4-7dec3a23762c")]
            public virtual RepoItemInfo SepetimInfo
            {
                get
                {
                    return _sepetimInfo;
                }
            }

            /// <summary>
            /// The SonKullanmaTarihi item.
            /// </summary>
            [RepositoryItem("12867755-7f46-4c3f-845a-587e69064ba5")]
            public virtual Ranorex.LabelTag SonKullanmaTarihi
            {
                get
                {
                    return _sonkullanmatarihiInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The SonKullanmaTarihi item info.
            /// </summary>
            [RepositoryItemInfo("12867755-7f46-4c3f-845a-587e69064ba5")]
            public virtual RepoItemInfo SonKullanmaTarihiInfo
            {
                get
                {
                    return _sonkullanmatarihiInfo;
                }
            }

            /// <summary>
            /// The CardCvv item.
            /// </summary>
            [RepositoryItem("35b90ca0-6510-440a-a6a8-14dbc05a5498")]
            public virtual Ranorex.InputTag CardCvv
            {
                get
                {
                    return _cardcvvInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CardCvv item info.
            /// </summary>
            [RepositoryItemInfo("35b90ca0-6510-440a-a6a8-14dbc05a5498")]
            public virtual RepoItemInfo CardCvvInfo
            {
                get
                {
                    return _cardcvvInfo;
                }
            }

            /// <summary>
            /// The GirişYap item.
            /// </summary>
            [RepositoryItem("dc81a9df-08f1-4207-b5f0-d28961770824")]
            public virtual Ranorex.PTag GirişYap
            {
                get
                {
                    return _girişyapInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap item info.
            /// </summary>
            [RepositoryItemInfo("dc81a9df-08f1-4207-b5f0-d28961770824")]
            public virtual RepoItemInfo GirişYapInfo
            {
                get
                {
                    return _girişyapInfo;
                }
            }

            /// <summary>
            /// The LoginEmail item.
            /// </summary>
            [RepositoryItem("75af5ade-7813-4037-bad6-8e0df8ed0ec3")]
            public virtual Ranorex.InputTag LoginEmail
            {
                get
                {
                    return _loginemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginEmail item info.
            /// </summary>
            [RepositoryItemInfo("75af5ade-7813-4037-bad6-8e0df8ed0ec3")]
            public virtual RepoItemInfo LoginEmailInfo
            {
                get
                {
                    return _loginemailInfo;
                }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComSepet item.
            /// </summary>
            [RepositoryItem("3b40e370-a2aa-4742-96f3-41ace53527a3")]
            public virtual Ranorex.ATag HttpsWwwTrendyolComSepet
            {
                get
                {
                    return _httpswwwtrendyolcomsepetInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComSepet item info.
            /// </summary>
            [RepositoryItemInfo("3b40e370-a2aa-4742-96f3-41ace53527a3")]
            public virtual RepoItemInfo HttpsWwwTrendyolComSepetInfo
            {
                get
                {
                    return _httpswwwtrendyolcomsepetInfo;
                }
            }

            /// <summary>
            /// The wait item.
            /// </summary>
            [RepositoryItem("3be0e26a-e836-46e8-b81b-97b76299d122")]
            public virtual Ranorex.PTag wait
            {
                get
                {
                    return _waitInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The wait item info.
            /// </summary>
            [RepositoryItemInfo("3be0e26a-e836-46e8-b81b-97b76299d122")]
            public virtual RepoItemInfo waitInfo
            {
                get
                {
                    return _waitInfo;
                }
            }

            /// <summary>
            /// The SepetiOnayla item.
            /// </summary>
            [RepositoryItem("b4fa2eef-74f9-4704-a3da-80962e50ede2")]
            public virtual Ranorex.SpanTag SepetiOnayla
            {
                get
                {
                    return _sepetionaylaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SepetiOnayla item info.
            /// </summary>
            [RepositoryItemInfo("b4fa2eef-74f9-4704-a3da-80962e50ede2")]
            public virtual RepoItemInfo SepetiOnaylaInfo
            {
                get
                {
                    return _sepetionaylaInfo;
                }
            }

            /// <summary>
            /// The PLayout folder.
            /// </summary>
            [RepositoryFolder("4de4f77a-011f-4b78-8294-de1f300e88c3")]
            public virtual Scenario6RepositoryFolders.PLayoutFolder PLayout
            {
                get { return _playout; }
            }

            /// <summary>
            /// The LoginRegister folder.
            /// </summary>
            [RepositoryFolder("5cdcdc80-ebfa-4dbe-942f-966b0872ac48")]
            public virtual Scenario6RepositoryFolders.LoginRegisterFolder LoginRegister
            {
                get { return _loginregister; }
            }
        }

        /// <summary>
        /// The PLayoutFolder folder.
        /// </summary>
        [RepositoryFolder("4de4f77a-011f-4b78-8294-de1f300e88c3")]
        public partial class PLayoutFolder : RepoGenBaseFolder
        {
            RepoItemInfo _kaydetvedevametInfo;
            RepoItemInfo _pcheckboxtextInfo;
            RepoItemInfo _kartbilgileriInfo;

            /// <summary>
            /// Creates a new PLayout  folder.
            /// </summary>
            public PLayoutFolder(RepoGenBaseFolder parentFolder) :
                    base("PLayout", ".//div[#'p-layout']", parentFolder, 30000, null, false, "4de4f77a-011f-4b78-8294-de1f300e88c3", "")
            {
                _kaydetvedevametInfo = new RepoItemInfo(this, "KaydetVeDevamEt", "aside/div/button[2]", "aside/div/button[2]", 30000, null, "645aadcf-4705-44c8-9610-88dbda9b41c3");
                _pcheckboxtextInfo = new RepoItemInfo(this, "PCheckboxText", "aside/div/div[1]/section//span", "aside/div/div[1]/section/div/label/span", 30000, null, "2416d72a-91c8-48af-8d48-2b1c94b7eca3");
                _kartbilgileriInfo = new RepoItemInfo(this, "KartBilgileri", "div/div[2]/div[2]/div[2]//span[@innertext='Kart Bilgileri']", "div/div[2]/div[2]/div[2]/div/div[1]/div[1]/span[@innertext='Kart Bilgileri']", 30000, null, "340e2a11-3a55-401b-9cde-f01df714bd7e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4de4f77a-011f-4b78-8294-de1f300e88c3")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4de4f77a-011f-4b78-8294-de1f300e88c3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The KaydetVeDevamEt item.
            /// </summary>
            [RepositoryItem("645aadcf-4705-44c8-9610-88dbda9b41c3")]
            public virtual Ranorex.ButtonTag KaydetVeDevamEt
            {
                get
                {
                    return _kaydetvedevametInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The KaydetVeDevamEt item info.
            /// </summary>
            [RepositoryItemInfo("645aadcf-4705-44c8-9610-88dbda9b41c3")]
            public virtual RepoItemInfo KaydetVeDevamEtInfo
            {
                get
                {
                    return _kaydetvedevametInfo;
                }
            }

            /// <summary>
            /// The PCheckboxText item.
            /// </summary>
            [RepositoryItem("2416d72a-91c8-48af-8d48-2b1c94b7eca3")]
            public virtual Ranorex.SpanTag PCheckboxText
            {
                get
                {
                    return _pcheckboxtextInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The PCheckboxText item info.
            /// </summary>
            [RepositoryItemInfo("2416d72a-91c8-48af-8d48-2b1c94b7eca3")]
            public virtual RepoItemInfo PCheckboxTextInfo
            {
                get
                {
                    return _pcheckboxtextInfo;
                }
            }

            /// <summary>
            /// The KartBilgileri item.
            /// </summary>
            [RepositoryItem("340e2a11-3a55-401b-9cde-f01df714bd7e")]
            public virtual Ranorex.SpanTag KartBilgileri
            {
                get
                {
                    return _kartbilgileriInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The KartBilgileri item info.
            /// </summary>
            [RepositoryItemInfo("340e2a11-3a55-401b-9cde-f01df714bd7e")]
            public virtual RepoItemInfo KartBilgileriInfo
            {
                get
                {
                    return _kartbilgileriInfo;
                }
            }
        }

        /// <summary>
        /// The LoginRegisterFolder folder.
        /// </summary>
        [RepositoryFolder("5cdcdc80-ebfa-4dbe-942f-966b0872ac48")]
        public partial class LoginRegisterFolder : RepoGenBaseFolder
        {
            RepoItemInfo _girişyap2Info;
            RepoItemInfo _girişyap1Info;
            RepoItemInfo _ueyeolInfo;

            /// <summary>
            /// Creates a new LoginRegister  folder.
            /// </summary>
            public LoginRegisterFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginRegister", ".//div[#'login-register']", parentFolder, 30000, null, false, "5cdcdc80-ebfa-4dbe-942f-966b0872ac48", "")
            {
                _girişyap2Info = new RepoItemInfo(this, "GirişYap2", ".//form[@action='https://www.trendyol.com/giris?cb=https%3A%2F%2Fwww.trendyol.com%2F']/?/?/span[@innertext='Giriş Yap']", ".//form/button/span[@innertext='Giriş Yap']", 30000, null, "159b3e74-ad17-455d-bf2f-5da7dc0c2ea8");
                _girişyap1Info = new RepoItemInfo(this, "GirişYap1", "div[2]/div/button[1]/span[@innertext='Giriş Yap']", ".//span[@innertext='Giriş Yap']", 30000, null, "9d7b112b-a643-4273-b178-8498feaf7cc6");
                _ueyeolInfo = new RepoItemInfo(this, "UEyeOl", "div[2]/div/button[2]/span[@innertext='Üye Ol']", ".//span[@innertext='Üye Ol']", 30000, null, "2cb38af1-672b-47e2-be92-b0bb5b9b0096");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5cdcdc80-ebfa-4dbe-942f-966b0872ac48")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5cdcdc80-ebfa-4dbe-942f-966b0872ac48")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GirişYap2 item.
            /// </summary>
            [RepositoryItem("159b3e74-ad17-455d-bf2f-5da7dc0c2ea8")]
            public virtual Ranorex.SpanTag GirişYap2
            {
                get
                {
                    return _girişyap2Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap2 item info.
            /// </summary>
            [RepositoryItemInfo("159b3e74-ad17-455d-bf2f-5da7dc0c2ea8")]
            public virtual RepoItemInfo GirişYap2Info
            {
                get
                {
                    return _girişyap2Info;
                }
            }

            /// <summary>
            /// The GirişYap1 item.
            /// </summary>
            [RepositoryItem("9d7b112b-a643-4273-b178-8498feaf7cc6")]
            public virtual Ranorex.SpanTag GirişYap1
            {
                get
                {
                    return _girişyap1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap1 item info.
            /// </summary>
            [RepositoryItemInfo("9d7b112b-a643-4273-b178-8498feaf7cc6")]
            public virtual RepoItemInfo GirişYap1Info
            {
                get
                {
                    return _girişyap1Info;
                }
            }

            /// <summary>
            /// The UEyeOl item.
            /// </summary>
            [RepositoryItem("2cb38af1-672b-47e2-be92-b0bb5b9b0096")]
            public virtual Ranorex.SpanTag UEyeOl
            {
                get
                {
                    return _ueyeolInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOl item info.
            /// </summary>
            [RepositoryItemInfo("2cb38af1-672b-47e2-be92-b0bb5b9b0096")]
            public virtual RepoItemInfo UEyeOlInfo
            {
                get
                {
                    return _ueyeolInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
